# Generated by Django 5.2.2 on 2025-06-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopeeConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('partner_id', models.BigIntegerField()),
                ('shop_id', models.BigIntegerField()),
                ('partner_key', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
    ]
